spring.datasource.url = jdbc:postgresql://localhost:5332/booking_database
datasource.username = admin
datasource.password = passw0rd!
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql = true
jwt.secret=K1uT8m9ZxPqLs3S2yVxNwH3aQeXc7jF6
jwt.expiration=86400000