package com.razza.bookingsystem.config;

import com.razza.bookingsystem.domain.*;
import com.razza.bookingsystem.repository.*;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.time.LocalDateTime;

/**
 * Initializes sample data in the database at application startup.
 *
 * This class uses a {@link CommandLineRunner} bean to insert:
 *  Tenants
 *  Users (with encoded passwords)
 *  Events
 *  Bookings
 * It is primarily intended for development and testing purposes.
 * In production, users would typically sign up via the API, and
 * bookings would be created via application logic.
 */
@Configuration
@RequiredArgsConstructor
public class DataInitializer {

    private final TenantRepository tenantRepository;
    private final UserRepository userRepository;
    private final EventRepository eventRepository;
    private final BookingRepository bookingRepository;
    private final PasswordEncoder passwordEncoder;

    /**
     * Creates a {@link CommandLineRunner} that seeds initial data into the database.
     *
     * This runner executes automatically after the Spr52d5ef65-2944-4e23-a81d-0c3a6d9096a7ing context is initialized.
     * It creates:
         Two tenants (Tenant A and Tenant B)
     *   Three users (Alice, Bob, Admin) with passwords encoded via {@link PasswordEncoder}
     *   Two events, each linked to a tenant
     *   Two bookings, each linking a user and an event
     *
     *  All IDs for events and bookings are now generated by Hibernate to avoid
     *  foreign key constraint issues.
     * @return a {@link CommandLineRunner} that seeds the database
     */
    @Bean
    CommandLineRunner initData() {
        return args -> {

            Tenant tenantA = new Tenant();
            tenantA.setName("Tenant A");
            Tenant tenantB = new Tenant();
            tenantB.setName("Tenant B");

            tenantRepository.save(tenantA);
            tenantRepository.save(tenantB);

            User alice = new User();
            alice.setEmail("alice@example.com");
            alice.setPassword(passwordEncoder.encode("password"));
            alice.setRole(Role.USER);
            alice.setTenant(tenantA);

            User bob = new User();
            bob.setEmail("bob@example.com");
            bob.setPassword(passwordEncoder.encode("password"));
            bob.setRole(Role.USER);
            bob.setTenant(tenantB);

            User admin = new User();
            admin.setEmail("admin@example.com");
            admin.setPassword(passwordEncoder.encode("admin_pass"));
            admin.setRole(Role.ADMIN);
            admin.setTenant(tenantA);

            userRepository.save(alice);
            userRepository.save(bob);
            userRepository.save(admin);

            Event event1 = Event.builder()
                    .name("Spring Boot Workshop")
                    .description("Learn Spring Boot basics")
                    .location("Room 101")
                    .date(LocalDateTime.now().plusDays(1))
                    .totalCapacity(30)
                    .availableCapacity(28)
                    .tenant(tenantA)
                    .status(Status.CONFIRMED)
                    .build();

            Event event2 = Event.builder()
                    .name("Docker Deep Dive")
                    .description("Hands-on Docker session")
                    .location("Room 202")
                    .date(LocalDateTime.now().plusDays(2))
                    .totalCapacity(25)
                    .availableCapacity(24)
                    .tenant(tenantB)
                    .status(Status.CONFIRMED)
                    .build();

            eventRepository.save(event1);
            eventRepository.save(event2);

            Booking booking1 = Booking.builder()
                    .userId(alice.getId())
                    .event(event1)
                    .tenant(tenantA)
                    .quantity(2)
                    .status(Status.CONFIRMED)
                    .createdAt(LocalDateTime.now())
                    .build();

            Booking booking2 = Booking.builder()
                    .userId(bob.getId())
                    .event(event2)
                    .tenant(tenantB)
                    .quantity(1)
                    .status(Status.CONFIRMED)
                    .createdAt(LocalDateTime.now())
                    .build();

            bookingRepository.save(booking1);
            bookingRepository.save(booking2);
        };
    }
}