package com.razza.bookingsystem.config;

import com.razza.bookingsystem.domain.*;
import com.razza.bookingsystem.repository.*;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.time.LocalDateTime;

/**
 * Initializes sample data in the database at application startup.
 *
 * This class uses a {@link CommandLineRunner} bean to insert:
 *  Tenants
 *  Users (with encoded passwords)
 *  Events
 *  Bookings
 * It is primarily intended for development and testing purposes.
 * In production, users would typically sign up via the API, and
 * bookings would be created via application logic.
 */
@Configuration
@RequiredArgsConstructor
public class DataInitializer {

    private final TenantRepository tenantRepository;
    private final UserRepository userRepository;
    private final EventRepository eventRepository;
    private final BookingRepository bookingRepository;
    private final PasswordEncoder passwordEncoder;

    /**
     * This class uses a CommandLineRunner bean to seed initial data.
     *
     * Bootstrap note:
     * Since tenants and their first admins cannot be created via the API,
     * this initializer creates one ADMIN user for each tenant at startup.
     *
     * Passwords are encoded using the provided PasswordEncoder before being saved
     * to the database.
     *
     * All IDs for events and bookings are generated by Hibernate to avoid foreign
     * key constraint issues.
     *
     * @return a CommandLineRunner that seeds the database
     */
    @Bean
    CommandLineRunner initData() {
        return new CommandLineRunner() {
            @Override
            public void run(String... args) throws Exception {
                Tenant tenantA = new Tenant();
                tenantA.setName("Tenant A");
                Tenant tenantB = new Tenant();
                tenantB.setName("Tenant B");
                Tenant tenantC = new Tenant();
                tenantC.setName("Tenant C");


                tenantRepository.save(tenantA);
                tenantRepository.save(tenantB);
                tenantRepository.save(tenantC);

                User alice = new User();
                alice.setEmail("alice@example.com");
                alice.setPassword(passwordEncoder.encode("password"));
                alice.setRole(Role.USER);
                alice.setTenant(tenantA);

                User ariana = new User();
                ariana.setEmail("ariana@example.com");
                ariana.setPassword(passwordEncoder.encode("password"));
                ariana.setRole(Role.USER);
                ariana.setTenant(tenantA);

                User adminA = new User();
                adminA.setEmail("adminA@example.com");
                adminA.setPassword(passwordEncoder.encode("adminA_pass"));
                adminA.setRole(Role.ADMIN);
                adminA.setTenant(tenantA);

                userRepository.save(alice);
                userRepository.save(ariana);
                userRepository.save(adminA);

                User bob = new User();
                bob.setEmail("bob@example.com");
                bob.setPassword(passwordEncoder.encode("password"));
                bob.setRole(Role.USER);
                bob.setTenant(tenantB);

                User bert = new User();
                bert.setEmail("bert@example.com");
                bert.setPassword(passwordEncoder.encode("password"));
                bert.setRole(Role.USER);
                bert.setTenant(tenantB);

                User adminB = new User();
                adminB.setEmail("adminB@example.com");
                adminB.setPassword(passwordEncoder.encode("adminB_pass"));
                adminB.setRole(Role.ADMIN);
                adminB.setTenant(tenantB);

                userRepository.save(bob);
                userRepository.save(bert);
                userRepository.save(adminB);

                User adminC = new User();
                adminC.setEmail("adminC@example.com");
                adminC.setPassword(passwordEncoder.encode("adminC_pass"));
                adminC.setRole(Role.ADMIN);
                adminC.setTenant(tenantC);

                userRepository.save(adminC);

                Event event1 = Event.builder()
                        .name("Flowers")
                        .description("Learn to grow flowers")
                        .location("Room 101")
                        .date(LocalDateTime.now().plusDays(1))
                        .totalCapacity(30)
                        .availableCapacity(28)
                        .tenant(tenantA)
                        .status(Status.CONFIRMED)
                        .build();

                Event event2 = Event.builder()
                        .name("Rocks")
                        .description("Learn different rocks")
                        .location("Room 202")
                        .date(LocalDateTime.now().plusDays(2))
                        .totalCapacity(25)
                        .availableCapacity(24)
                        .tenant(tenantB)
                        .status(Status.CONFIRMED)
                        .build();

                Event event3 = Event.builder()
                        .name("Origami")
                        .description("Learn paper origami")
                        .location("Room 303")
                        .date(LocalDateTime.now().plusDays(1))
                        .totalCapacity(15)
                        .availableCapacity(8)
                        .tenant(tenantA)
                        .status(Status.CONFIRMED)
                        .build();

                Event event4 = Event.builder()
                        .name("Yoga")
                        .description("Learn yoga")
                        .location("Room 404")
                        .date(LocalDateTime.now().plusDays(2))
                        .totalCapacity(50)
                        .availableCapacity(50)
                        .tenant(tenantC)
                        .status(Status.CONFIRMED)
                        .build();

                Event event5 = Event.builder()
                        .name("Running")
                        .description("Learn how to run faster")
                        .location("Room 505")
                        .date(LocalDateTime.now().plusDays(3))
                        .totalCapacity(25)
                        .availableCapacity(25)
                        .tenant(tenantB)
                        .status(Status.CONFIRMED)
                        .build();

                eventRepository.save(event1);
                eventRepository.save(event2);
                eventRepository.save(event3);
                eventRepository.save(event4);
                eventRepository.save(event5);

                Booking booking1 = Booking.builder()
                        .userId(alice.getId())
                        .event(event1)
                        .tenant(tenantA)
                        .quantity(2)
                        .status(Status.CONFIRMED)
                        .createdAt(LocalDateTime.now())
                        .build();

                Booking booking2 = Booking.builder()
                        .userId(bob.getId())
                        .event(event2)
                        .tenant(tenantB)
                        .quantity(1)
                        .status(Status.CONFIRMED)
                        .createdAt(LocalDateTime.now())
                        .build();

                Booking booking3 = Booking.builder()
                        .userId(ariana.getId())
                        .event(event3)
                        .tenant(tenantA)
                        .quantity(5)
                        .status(Status.CONFIRMED)
                        .createdAt(LocalDateTime.now())
                        .build();

                Booking booking4 = Booking.builder()
                        .userId(alice.getId())
                        .event(event3)
                        .tenant(tenantA)
                        .quantity(2)
                        .status(Status.CONFIRMED)
                        .createdAt(LocalDateTime.now())
                        .build();

                bookingRepository.save(booking1);
                bookingRepository.save(booking2);
                bookingRepository.save(booking3);
                bookingRepository.save(booking4);
            }
        };
    }
}
