package com.razza.bookingsystem.config;

import com.razza.bookingsystem.domain.*;
import com.razza.bookingsystem.repository.*;
import com.razza.bookingsystem.service.AuthService;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.time.OffsetDateTime;
import java.util.*;

// AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

/**
 * Initializes sample data in the database at application startup.
 *
 * This class uses a {@link CommandLineRunner} bean to insert:
 *  Venues
 *  Users (with encoded passwords)
 *  Events
 *  Bookings
 * It is primarily intended for development and testing purposes.
 * In production, users would typically sign up via the API, and
 * bookings would be created via application logic.
 */
@Configuration     //@Configuration because this class is a source of beans (CommandLineRunner)
@RequiredArgsConstructor
public class DataInitializer {

    private final VenueRepository venueRepository;
    private final UserRepository userRepository;
    private final EventRepository eventRepository;
    private final BookingRepository bookingRepository;
    private final PerformanceRepository performanceRepository;
    private final AvailabilityRepository availabilityRepository;
    private final PasswordEncoder passwordEncoder;
    private final AuthService authService;

    /**
     * This class uses a CommandLineRunner bean to seed initial data.
     *
     * Bootstrap note:
     * Since venues and their first admins cannot be created via the API,
     * this initializer creates one ADMIN user for each venue at startup.
     *
     * Passwords are encoded using the provided PasswordEncoder before being saved
     * to the database.
     *
     * All IDs for events and bookings are generated by Hibernate to avoid foreign
     * key constraint issues.
     *
     * @return a CommandLineRunner that seeds the database
     */
    @Bean
    CommandLineRunner initData() {      //CommandLineRunner is an interface that runs code just after the application startup
        return new CommandLineRunner() {
            @Override
            public void run(String... args) throws Exception {      // run(String... args) is the run method signature, it can't be changed, it means the number of arguments passed to run() is variable, in this case none, but from command line it could be called with arguments
                Venue venueA = new Venue();
                venueA.setName("venue A");
                Venue venueB = new Venue();
                venueB.setName("venue B");
                Venue venueC = new Venue();
                venueC.setName("venue C");


                venueRepository.save(venueA);
                venueRepository.save(venueB);
                venueRepository.save(venueC);

                User ashley = User.builder()
                        .name("ashley")
                        .birthDate(OffsetDateTime.parse("2000-01-01T00:00:00+02:00"))
                        .email("ashley@example.com")
                        .password(passwordEncoder.encode("password"))
                        .role(Role.GUEST)
                        .venue(venueA)
                        .status(Status.CONFIRMED)
                        .build();

                User alice = User.builder()
                        .name("alice")
                        .birthDate(OffsetDateTime.parse("2000-01-01T00:00:00+02:00"))
                        .email("alice@example.com")
                        .password(passwordEncoder.encode("password"))
                        .role(Role.GUEST)
                        .venue(venueA)
                        .status(Status.CONFIRMED)
                        .build();

                User ariana = User.builder()
                        .name("ariana")
                        .birthDate(OffsetDateTime.parse("2010-01-01T00:00:00+02:00"))
                        .email("ariana@example.com")
                        .password(passwordEncoder.encode("password"))
                        .role(Role.GUEST)
                        .venue(venueA)
                        .status(Status.CONFIRMED)
                        .build();

                User adam = User.builder()
                        .name("adam")
                        .birthDate(OffsetDateTime.parse("2000-01-01T00:00:00+02:00"))
                        .email("adam@example.com")
                        .password(passwordEncoder.encode("password"))
                        .role(Role.PERFORMER)
                        .venue(venueA)
                        .status(Status.CONFIRMED)
                        .performances(new HashSet<>(Set.of(
                                Performance.builder()
                                .name("jazz")
                                .description("jazz session")
                                .duration(120)
                                .performanceType(PerformanceType.LIVE_MUSIC)
                                .build(),
                                Performance.builder()
                                .name("rock")
                                .description("rock session")
                                .duration(120)
                                .performanceType(PerformanceType.LIVE_MUSIC)
                                .build())
                                ))
                        .availability(
                                new Availability(true,true,true,true,false,false,false)
                        )
                        .build();

                adam.getAvailability().setUser(adam);
                userRepository.save(adam);

                for(Performance performance : adam.getPerformances()){
                    performance.setUser(adam);
                    performanceRepository.save(performance);
                }

                User alex = User.builder()
                        .name("alex")
                        .birthDate(OffsetDateTime.parse("2000-01-01T00:00:00+02:00"))
                        .email("alex@example.com")
                        .password(passwordEncoder.encode("password"))
                        .role(Role.PERFORMER)
                        .venue(venueA)
                        .status(Status.CONFIRMED)
                        .performances(new HashSet<>(Set.of(
                                Performance.builder()
                                        .name("blues")
                                        .description("blues session")
                                        .duration(120)
                                        .performanceType(PerformanceType.LIVE_MUSIC)
                                        .build())
                        ))
                        .availability(
                                new Availability(false,false,true,false,false,true,true)
                        )
                        .build();

                alex.getAvailability().setUser(alex);
                userRepository.save(alex);

                for(Performance performance : alex.getPerformances()){
                    performance.setUser(alex);
                    performanceRepository.save(performance);
                }

                User adrien = User.builder()
                        .name("adrien")
                        .birthDate(OffsetDateTime.parse("2000-01-01T00:00:00+02:00"))
                        .email("adrien@example.com")
                        .password(passwordEncoder.encode("password"))
                        .role(Role.PERFORMER)
                        .venue(venueA)
                        .status(Status.CONFIRMED)
                        .performances(new HashSet<>(Set.of(
                                Performance.builder()
                                        .name("funk")
                                        .description("funky session")
                                        .duration(120)
                                        .performanceType(PerformanceType.LIVE_MUSIC)
                                        .build())
                        ))
                        .availability(
                                new Availability(false,false,false,true,true,true,false)
                        )
                        .build();

                adrien.getAvailability().setUser(adrien);
                userRepository.save(adrien);

                for(Performance performance : adrien.getPerformances()){
                    performance.setUser(adrien);
                    performanceRepository.save(performance);
                }

                User adminA = User.builder()
                        .name("adminA")
                        .birthDate(OffsetDateTime.parse("2000-01-01T00:00:00+02:00"))
                        .email("adminA@example.com")
                        .password(passwordEncoder.encode("adminA_pass"))
                        .role(Role.ADMIN)
                        .venue(venueA)
                        .status(Status.CONFIRMED)
                        .build();

                userRepository.save(alice);
                userRepository.save(ariana);
                userRepository.save(ashley);
                userRepository.save(adminA);

                User bob = User.builder()
                        .name("bob")
                        .birthDate(OffsetDateTime.parse("2000-01-01T00:00:00+02:00"))
                        .email("bob@example.com")
                        .password(passwordEncoder.encode("password"))
                        .role(Role.GUEST)
                        .venue(venueB)
                        .status(Status.CONFIRMED)
                        .build();

                User bert = User.builder()
                        .name("bert")
                        .birthDate(OffsetDateTime.parse("2000-01-01T00:00:00+02:00"))
                        .email("bert@example.com")
                        .password(passwordEncoder.encode("password"))
                        .role(Role.GUEST)
                        .venue(venueB)
                        .status(Status.CONFIRMED)
                        .build();

                User benjamin = User.builder()
                        .name("benjamin")
                        .birthDate(OffsetDateTime.parse("2000-01-01T00:00:00+02:00"))
                        .email("benjamin@example.com")
                        .password(passwordEncoder.encode("password"))
                        .role(Role.PERFORMER)
                        .venue(venueB)
                        .status(Status.CONFIRMED)
                        .performances(new HashSet<>(Set.of(
                                Performance.builder()
                                        .name("cabaret")
                                        .description("cabaret session")
                                        .duration(120)
                                        .performanceType(PerformanceType.COMEDY)
                                        .build())
                        ))
                        .availability(
                                new Availability(false,false,false,false,true,true,true)
                        )
                        .build();

                benjamin.getAvailability().setUser(benjamin);
                userRepository.save(benjamin);

                for(Performance performance : benjamin.getPerformances()){
                    performance.setUser(benjamin);
                    performanceRepository.save(performance);
                }


                User adminB = User.builder()
                        .name("adminB")
                        .birthDate(OffsetDateTime.parse("2000-01-01T00:00:00+02:00"))
                        .email("adminB@example.com")
                        .password(passwordEncoder.encode("adminB_pass"))
                        .role(Role.ADMIN)
                        .venue(venueB)
                        .status(Status.CONFIRMED)
                        .build();

                userRepository.save(bob);
                userRepository.save(bert);
                userRepository.save(adminB);

                Event event1 = Event.builder()
                        .name("Funky jazz event")
                        .description("Artists will play jazz and funk")
                        .location("main bar")
                        .date(OffsetDateTime.parse("2026-07-01T18:00:00+02:00"))
                        .bookingPolicy(new BookingPolicy(30,26))
                        .venue(venueA)
                        .status(Status.CONFIRMED)
                        .schedule(List.of(
                                TimeSlot.builder()
                                        .userEmail("adam@example.com")
                                        .startTime(OffsetDateTime.parse("2026-06-01T18:00:00+02:00"))
                                        .endTime(OffsetDateTime.parse("2026-06-01T20:00:00+02:00"))
                                        .performanceId(userRepository.findByEmailAndVenue("adam@example.com", venueA).get().getPerformances().stream().filter(performance -> performance.getName().equals("jazz")).findFirst().get().getId())
                                        .build(),
                                TimeSlot.builder()
                                        .userEmail("adrien@example.com")
                                        .startTime(OffsetDateTime.parse("2026-06-01T20:00:00+02:00"))
                                        .endTime(OffsetDateTime.parse("2026-06-01T22:00:00+02:00"))
                                        .performanceId(userRepository.findByEmailAndVenue("adrien@example.com", venueA).get().getPerformances().stream().filter(performance -> performance.getName().equals("funk")).findFirst().get().getId())
                                        .build()

                        ))
                        .eighteenPlus(false)
                        .build();

                Event event2 = Event.builder()
                        .name("blues, rock and jazz event")
                        .description("Artists will play blues, rock and jazz")
                        .location("main bar")
                        .date(OffsetDateTime.parse("2026-07-02T19:00:00+02:00"))
                        .bookingPolicy(new BookingPolicy(30))
                        .venue(venueA)
                        .status(Status.CONFIRMED)
                        .schedule(List.of(
                                TimeSlot.builder()
                                        .userEmail("alex@example.com")
                                        .startTime(OffsetDateTime.parse("2026-06-02T19:00:00+02:00"))
                                        .endTime(OffsetDateTime.parse("2026-06-02T21:00:00+02:00"))
                                        .performanceId(userRepository.findByEmailAndVenue("alex@example.com", venueA).get().getPerformances().stream().filter(performance -> performance.getName().equals("blues")).findFirst().get().getId())
                                        .build(),
                                TimeSlot.builder()
                                        .userEmail("adam@example.com")
                                        .startTime(OffsetDateTime.parse("2026-06-02T21:00:00+02:00"))
                                        .endTime(OffsetDateTime.parse("2026-06-02T23:00:00+02:00"))
                                        .performanceId(userRepository.findByEmailAndVenue("adam@example.com", venueA).get().getPerformances().stream().filter(performance -> performance.getName().equals("rock")).findFirst().get().getId())
                                        .build(),
                                TimeSlot.builder()
                                        .userEmail("adam@example.com")
                                        .startTime(OffsetDateTime.parse("2026-06-02T23:00:00+02:00"))
                                        .endTime(OffsetDateTime.parse("2026-06-03T01:00:00+02:00"))
                                        .performanceId(userRepository.findByEmailAndVenue("adam@example.com", venueA).get().getPerformances().stream().filter(performance -> performance.getName().equals("jazz")).findFirst().get().getId())
                                        .build()

                        ))
                        .eighteenPlus(false)
                        .build();

                Event event3 = Event.builder()
                        .name("funky music event")
                        .description("Adrien will play funky music")
                        .location("the underground bar")
                        .date(OffsetDateTime.parse("2026-07-02T20:00:00+02:00"))
                        .bookingPolicy(null)
                        .venue(venueA)
                        .status(Status.CONFIRMED)
                        .schedule(List.of(
                                TimeSlot.builder()
                                        .userEmail("adrien@example.com")
                                        .startTime(OffsetDateTime.parse("2026-06-02T20:00:00+02:00"))
                                        .endTime(OffsetDateTime.parse("2026-06-02T22:00:00+02:00"))
                                        .performanceId(userRepository.findByEmailAndVenue("adrien@example.com", venueA).get().getPerformances().stream().filter(performance -> performance.getName().equals("funk")).findFirst().get().getId())
                                        .build()
                        ))
                        .eighteenPlus(true)
                        .build();

                Event event4 = Event.builder()
                        .name("cabaret")
                        .description("cabaret by Benjamin")
                        .location("main hall")
                        .date(OffsetDateTime.parse("2026-07-01T21:00:00+02:00"))
                        .bookingPolicy(new BookingPolicy(50,45))
                        .venue(venueB)
                        .status(Status.CONFIRMED)
                        .schedule(List.of(
                                TimeSlot.builder()
                                        .userEmail("benjamin@example.com")
                                        .startTime(OffsetDateTime.parse("2026-06-01T21:00:00+02:00"))
                                        .endTime(OffsetDateTime.parse("2026-06-01T23:00:00+02:00"))
                                        .performanceId(userRepository.findByEmailAndVenue("benjamin@example.com", venueB).get().getPerformances().stream().filter(performance -> performance.getName().equals("cabaret")).findFirst().get().getId())
                                        .build()
                        ))
                        .eighteenPlus(false)
                        .build();

                eventRepository.save(event1);
                eventRepository.save(event2);
                eventRepository.save(event3);
                eventRepository.save(event4);

                Booking booking1 = Booking.builder()
                        .user(alice)
                        .event(event1)
                        .venue(venueA)
                        .quantity(2)
                        .status(Status.CONFIRMED)
                        .createdAt(OffsetDateTime.now())
                        .build();

                Booking booking2 = Booking.builder()
                        .user(ariana)
                        .event(event1)
                        .venue(venueA)
                        .quantity(2)
                        .status(Status.CONFIRMED)
                        .createdAt(OffsetDateTime.now())
                        .build();

                Booking booking4 = Booking.builder()
                        .user(bob)
                        .event(event4)
                        .venue(venueB)
                        .quantity(5)
                        .status(Status.CONFIRMED)
                        .createdAt(OffsetDateTime.now())
                        .build();

                bookingRepository.save(booking1);
                bookingRepository.save(booking2);
                bookingRepository.save(booking4);
            }
        };
    }
}
